Feature/haeun step1
C4-ComeTrue/my-storage pull request #2
Opened 2023-10-17 14:19 UTC by pear96

상세 내용은 각 커밋 메세지에 자세히 적어두었습니다.
PR에는 고민점을 동일하게 작성해 두겠습니다.

[FileMetaData]
- fileId에 대해 Getter로 사용될 일이 없는데, fileId만 제외한 다른 필드에 다 @getter를 붙일지, 아니면 클래스에 @getter를 붙인 것을 유지할지 고민입니다.

[FileRepository]
- 파일 로컬 저장 이름이 UUID로 약간 길어졌는데, 이로 인해 검색 성능에 큰 악영향을 주는지 궁금합니다.
  파일 로컬 저장 이름 VS 파일 원본 이름 + 사용자 이름 중에 어느 쿼리가 나을지 고민됩니다.
  (대신 이를 위해 DB에 한 사용자의 같은 파일명에 대해 (1), (2)등 넘버링으로 구분해서 저장해야함...)

[FileException]
- CustomException에 대해 메세지를 포함할까 고민이 됩니다. 
- 메세지를 포함하지 않은 이유는 FileService에서 예외를 던질 때 직접 메세지를 작성하고 싶지 않았기 때문입니다.
- 메세지에 대해 enum을 만들까요..?

[ApiExceptionRes]
- 예외 발생시 클라이언트에 응답을 전달하는 DTO입니다.
- FileException에서 메세지를 전달하지 않기 때문에, 마찬가지로 메세지를 포함할지 말지 고민이 됩니다.
  만약 화면단이 있다면, 오류 응답에 대해 메세지가 일치했을 때 처리하기보단, 응답 코드에 따라 화면을 바꿀 것이라고 생각하기 때문입니다.

[ExceptionHandlingController]
- 컨트롤러에서 발생한 예외를 처리하는 클래스를 생성했습니다.
- ConstraintViolatinException은 클라이언트가 전달한 값이 조건을 만족시키지 못할 때 발생합니다.
- MissingServletRequestPartException은 클라이언트가 아예 어떠한 값을 전송하지 않았을 때 발생합니다.
- 실제라면 Missing~ 예외는 발생하지 않겠죠..?

[FileControllerTest]
- 처음에 FileService에 대해 테스트를 만들다가, 컨트롤러 테스트로 수정하였습니다. 컨트롤러가 맞을까요?

2023-10-17 14:25 UTC, pear96 commented
application-local.yml이 없어서 빌드에 실패했습니다.
DB정보 application-local.yml에 따로 저장해뒀는데, 그냥 올려버려야 하나요?
제 로컬 DB가 털릴 일이 없을 것 같긴 한데..

2023-10-17 14:52 UTC, kochungcheon reviewed
고생하셨습니다!😀

2023-10-17 14:52 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/repository/FileRepository.java
> +public interface FileRepository extends JpaRepository<FileMetaData, Long> {
Jpa 레포지토리를 타고 올라가면 어떤 인터페이스가 있나요!?

2023-10-17 14:52 UTC, kochungcheon commented on src/test/java/com/c4cometrue/mystorage/controller/FileControllerTest.java
> +        MultipartFile multipartFile = new MockMultipartFile(
테스트에 자주 사용되는 변수들은 어떤 식으로 관리하면 좋을 까요!?

2023-10-17 15:54 UTC, VSFe requested changes
수고하셨습니다~~
이후 폴더를 고려하면, 현재 구조에서 유지되어야 할 점과, 변경되어야 할 수도 있는 점이 있을텐데, 그 부분도 잘 생각해보면 좋을 것 같습니다~~~~

2023-10-17 15:54 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/controller/FileController.java
> +    @PostMapping("")
""은 생략 가능합니다.

2023-10-17 15:54 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/controller/FileController.java
> +    public ResponseEntity<String> deleteFile(@NotBlank @RequestParam("filename") String fileStorageName,
기왕이면 `@RequestParam("~~~")` 을 쓰는 것 보단, 외부에서 받는 이름과 내부에서 사용하는 변수의 이름을 통일시키고 제거하는게 더 혼선이 적을 것 같아요.

2023-10-17 15:54 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/dto/response/CreateFileRes.java
> +@Getter
@Setter 를 사용하지 않으면, 과감하게 제거해주세요.

Java의 트랜드가 FP와 Switch Pattern Matching으로 변화하면서, **불변 클래스**의 중요도가 좀 더 높아졌어요.
클래스를 불변으로 두게 되면 활용할 수 있는 범위가 넓어지기도 하고, 기본적으로 DTO는 불변임이 전제된 상태에서 개발을 많이 하는 편이에요.

2023-10-17 15:54 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/dto/response/CreateFileRes.java
> +@Setter
추가적으로, Java 17을 쓰고 있기 때문에, 불변 클래스를 사용한다면 `Record`로 변경해서 사용하는 것을 권장합니다.

참고: https://s7won.tistory.com/2

2023-10-17 15:54 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/entity/FileMetaData.java
> +    private int fileId;
일반적으로 PK는 long으로 많이 사용해요.

2023-10-17 15:54 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/repository/FileRepository.java
> +public interface FileRepository extends JpaRepository<FileMetaData, Long> {
그러게요

2023-10-17 15:54 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/service/FileService.java
> +        FileMetaData fileMetaData = fileRepository.findByFileStorageName(fileStorageName);
`optional`로 받아서 elseThrow로 처리하는게 좀 더 자연스러울 것 같아요.

2023-10-17 15:54 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/service/FileService.java
> +            Files.delete(filePath);
물리적인 파일 삭제 -> DB 삭제
DB 삭제 -> 물리적인 파일 삭제

어떤 순서로 접근하는게 맞을까요? 왜 그럴까요?

2023-10-17 15:54 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/exception/ExceptionHandlingController.java
> +    @ExceptionHandler(value = {FileException.class})
선언하는 Exception의 종류가 너무 많아질 위험이 있습니다.
Exception을 하나로 묶어버리고, 내부에서 우리가 어떤 문제가 있는지 구분할 수 있도록 만들 순 없을까요?

(요건 감이 안 오면 그냥 물어보세요. 힌트 드림)

2023-10-17 15:54 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/exception/ApiExceptionRes.java
> +public class ApiExceptionRes {
시연한 것 처럼, 최소한의 파일을 사용하여 발생할 수 있는 서비스적인 에러를 관리할 수 있게 해 주세요.

+ Resolver는 안 보여줬으니까, 알아서 파이팅!

2023-10-17 15:54 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/service/FileService.java
> +            return ResponseEntity.ok(new CreateFileRes(fileMetaData));
ResponseEntity로의 반환은 Controller 단에서 수행하는게 좋습니다.
비즈니스 로직에서는 순수한 CreateFileRes를 반환하게 해 주세요.

(+ Created - HttpStatus 201)
(++ 굳이 ResponseEntity 쓰지 말고, `@ResponseStatus(HttpStatus.CREATED)`를 Controller method에 삽입해도 됩니다.)

2023-10-17 15:54 UTC, VSFe commented on src/test/java/com/c4cometrue/mystorage/controller/FileControllerTest.java
> +class FileControllerTest {
통합테스트를 사용하고 있네요.
전체적인 흐름을 잡기 위해 통합테스트를 사용하고 있다면, 아예 클래스 이름을 분리해서 쓰는 것을 권장합니다.

일반적으로 클래스 이름으로 테스트를 만들게 되면, 이는 해당 클래스 자체의 메서드가 정상적으로 동작하는지를 확인하기 위해 수행하는 것이라서, 대부분 유닛테스트로 진행합니다. (외부 영향을 받는 것들은 철저하게 Mocking 하면서)

2023-10-17 15:54 UTC, VSFe commented on src/test/java/com/c4cometrue/mystorage/controller/FileControllerTest.java
> +        assertThrows(ConstraintViolationException.class,
TMI인데, assertThrows의 반환값은 반환된 그 예외 자체입니다.
상황에 따라서 해당 값을 받아서 추가로 검증을 해야할 수도 있어요.

2023-10-19 14:58 UTC, pear96 commented on src/main/java/com/c4cometrue/mystorage/repository/FileRepository.java
> +public interface FileRepository extends JpaRepository<FileMetaData, Long> {
Repository<T, ID> : 중앙 저장소 마커 인터페이스
└ PagingAndSortingRepository<T, ID> : 엔티디들을 페이지네이션, 정렬하는 레포지토리
    └ ListPagingAndSortingRepository<T, ID> : List에 담아 반환해줌
└ CrudRepository<T, ID> : save, find, delete, count 등 CRUD 수행
    └ ListCrudRepository<T, ID> : saveAll, findAll 의 결과를 List에 담아 반환
QueryByExampleExecutor<T> : 예제(찾고싶은 값을 가진Entity)객체를 생성해서, 이와 일치하는 엔티티 반환

등이 있군요...

2023-10-19 15:00 UTC, pear96 commented on src/test/java/com/c4cometrue/mystorage/controller/FileControllerTest.java
> +        MultipartFile multipartFile = new MockMultipartFile(
저도 청천님처럼 따로 클래스에 static 변수로 만드려고요!

2023-10-19 15:17 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/repository/FileRepository.java
> +public interface FileRepository extends JpaRepository<FileMetaData, Long> {
> * istPagingAndSortingRepository<T, ID> : List에 담아 반환해줌
> * CrudRepository<T, ID> : save, find, delete, count 등 CRUD 수행
>   
>   * ListCrudRepository<T, ID> : saveAll, findAll 의 결과를 List에 담아 반환
> 
> QueryByExampleExecutor : 예제(찾고싶은 값을 가진Entity)객체를 생성해서, 이와 일치하는 엔티티 반환
> 
> 등이 있군요...
그렇습니다 ! extends JpaRepository 한 순간부터 레포지토리 빈으로 등록 되기 떄문에 @Repository 는 빼셔도 될 거같아요!
https://stackoverflow.com/questions/51918181/why-isnt-necessary-repository-for-this-spring-boot-web-app

2023-10-19 15:35 UTC, pear96 commented on src/main/java/com/c4cometrue/mystorage/service/FileService.java
> +            Files.delete(filePath);
사용자 위주로 생각하면 실제 물리 파일은 서버에 남아있어도 DB에는 파일이 삭제되었다고 뜨는게 안전할 것 같은데.. (없는 파일에 대해 삭제, 다운로드 요청을 보낼 수 없으니까)
서버 저장소 위주로 생각하면 DB엔 없는 파일들이 저장소의 공간을 낭비하고 있을때, 이 파일들에 대해 DB에 없을 경우 삭제하는 배치를 따로 돌려야하고.. 근데 저장소에 파일이 무지 많다면 이것도 부담스럽겠네요..

차라리 DB에 있고 물리적 파일이 없을때, 해당 파일에 대해 요청이 오고 이때 파일을 못 찾는다면 DB에서 삭제하고 Not found를 보내야하나..??? 

근데 안정성을 더 중시한다면 역시 DB 삭제가 먼저 수행되는 것이 맞을 것 같습니다.

2023-10-22 16:59 UTC, VSFe approved these changes
(코드는 제가 라이브로 수정한게 좀 있으니 따로 코멘트 달라고 하진 않을게요. 하지만 다음 스텝부터는 리뷰에 대해서 청천님 PR 처럼 코멘트 부탁드릴게요.)

Code Smell만 나중에 수정해주세요~

2023-10-22 16:59 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/exception/ExceptionHandlingController.java
> +            logger.debug(exception.getMessage());
👍

2023-10-22 16:59 UTC, VSFe commented on src/main/resources/application.yml
> +  dir: C:/Users/pear/study/C4/storage
이후에 배포 고려했을 땐, profile로 분기해서 처리할 수 있도록 해주세요~
(지금 말고)

2023-10-22 17:12 UTC, pear96 commented on src/main/resources/application.yml
> +  dir: C:/Users/pear/study/C4/storage
넵 다음부터는 청천님처럼 코멘트 달겠습니다~

2023-10-22 17:13 UTC, merged