Feature/chung step2
C4-ComeTrue/my-storage pull request #6
Opened 2023-11-03 03:45 UTC by kochungcheon

[FolderMetadata]
- 폴더 속 폴더를 위해 부모 폴더 레코드 생성
- 폴더와 파일 구분을 위해 타입 레코드 생성
- 자주 사용되는 부모 폴더id는 인덱스 지정

[폴더 생성]
- 부모 폴더가 널 일 경우 루트 폴더에 폴더가 생성되도록 구현

[폴더 조회]
- 개별 유저의 폴더 및 파일 조회 가능하도록 구현, 루트 폴더에는 여러 유저의 폴더와 파일이 있을 수 있기 때문입니다

[파일 로직 변경]
- 폴더 기능 도입에 따른 변경
- 부모 폴더 레코드 추가
- 파일 조회 시 부모 폴더가 널 일 경우 처리

2023-11-03 11:56 UTC, VSFe commented on gradlew.bat
> +@rem you may not use this fileMetadata except in compliance with the License.
?

2023-11-08 17:46 UTC, VSFe requested changes
고생하라는 의미에서 (?) 리뷰 난이도를 올려봤습니다.

2023-11-08 17:46 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/folder/FolderDataAccessService.java
> +	// 적절한 예외 던져라
네

2023-11-08 17:46 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/meta/MetadataService.java
> +public class MetadataService {
굳이 분리할 필요가 있나하는 생각이 드네요.
MetadataService가 아닌 File 및 FolderService에도 메타데이터를 다루고 있지 않나요?

2023-11-08 17:46 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/meta/MetadataController.java
> +	public ResponseEntity<List<MetaResponse>> getFolderContents(FolderContentsRequest req) {
역할이 정확히 이해가 안 가네요.
폴더 목록 조회는 FolderController로 가는게 더 자연스럽지 않을까요?

2023-11-08 17:46 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/folder/FolderWriter.java
> +public interface FolderWriter {
2개 이상의 구현체가 있지 않은 상황에서, 굳이 Interface를 만들어야 할지에 대한 의문이 들어요.
특히나 Reader, Writer 모두 하나의 Service로 때려박은 상황에선 더더욱요.

2023-11-08 17:46 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/folder/FolderController.java
> +		folderService.createBy(req.userId(), req.userFolderName(), req.parentId());
~By 라는 네이밍을 사용한 이유가 있을까요?

2023-11-08 17:46 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/file/FileRepository.java
>  	@Query("SELECT CASE WHEN COUNT(m) > 0 "
JDK 17에서는 """ 으로 Text Block 생성이 가능합니다.

2023-11-08 17:46 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/file/FileRepository.java
> +		+ "(m.parentId = :parentId OR (m.parentId IS NULL AND :parentId IS NULL)) "
(parent_id, uploader_id, original_file_name) 의 인덱스가 필요하겠네요.

2023-11-08 17:46 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/file/FileDataAccessService.java
> +	public FileMetadata findBy(Long fileId, Long userId) {
existBy랑 매칭이 좀 어색해보이네요.
- existBy는 fileId로 Unique 하게 찾을 수 있어보이는데, findBy는 userId를 받는 이유가 있을까요?

2023-11-08 17:46 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/file/FileDataAccessService.java
> +	public List<FileMetadata> findChildBy(Long parentId, Long userId) {
fileId는 Unique 하게 만들었으면서, folderId는 Unique하게 만들지 않은 이유가 있나요?

2023-11-08 17:46 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/folder/FolderMetadata.java
> +	private MetadataType metadataType;
file과 folder의 테이블을 분리했으니, MetadataType 칼럼이 존재할 필요는 없어보이네요.

2023-11-08 17:46 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/folder/FolderRepository.java
> +	List<FolderMetadata> findByParentIdAndUploaderId(Long parentId, Long userId);
(parent_id, user_id) 에 대한 인덱스는 필요하겠네요.

2023-11-08 17:46 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/meta/MetadataService.java
> +		return Stream.concat(
파일이 4700개이고, 폴더가 5300개라면 어떻게 될까요?

2023-11-08 17:46 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/util/FolderUtil.java
> +			Files.createDirectories(path);
폴더 생성이 실패하는 케이스가 무엇이 있을까요?
굳이 물리적인 파일시스템 장애가 아니더라도, 지금 로직으로는 충분히 폴더 생성이 실패할 수 있어요.

2023-11-08 17:46 UTC, VSFe commented on src/main/resources/application.yml
위쪽에 적힌 `ddl-auto: create`는 제거하세요.
테스트할 데이터가 쌓일 수가 없는 구조네요...

통합 테스트를 구축하기 위한 property가 아닌 이상, 저걸 사용할 이유는 없습니다.

2023-11-08 17:46 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/meta/MetadataController.java
> +	@ResponseStatus(HttpStatus.CREATED)
물리적인 파일 업로드랑, 메타데이터 업로드를 별도로 분리한건가요?
그렇다면 왜 폴더에 대한 메타데이터 업로드 메서드는 존재하지 않는걸까요?

2023-11-08 17:46 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/folder/FolderDataAccessService.java
> +		folderMetadata.changeFolderName(folderName);
변경한 이름이 충돌되지 않는지는 확인하지 않네요.

2023-11-09 14:13 UTC, pear96 commented on src/main/java/com/c4cometrue/mystorage/dto/FileUploadRequest.java
> +public record FileUploadRequest(@NotNull(message = "파일을 전달해주세요") MultipartFile multipartFile,
`@NotNull`로 바꾸셨군요! 그런데 저는 테스트해보면 다른 입력값은 `MethodArgumentNotValidException`가 발생하는데 Multipartfile은 파일을 담지 않고 보내면 `ConstraintViolationException`가 발생하더라구요. 예외 핸들러에서 한번에 처리해줄 수 없는데 청천님은 어떻게 하려고 하셨나요..

2023-11-09 14:13 UTC, pear96 commented on src/main/java/com/c4cometrue/mystorage/dto/FolderContentsRequest.java
> +	@NotNull(message = "사용자 id는 널이 될 수 없습니다") long userId
왜 `Long`과 `long` 으로 구분지으셨는지 궁금합니다.. 조회용 DTO같은데 folderId는 null이어도 되나요?

2023-11-09 14:13 UTC, pear96 commented on src/main/java/com/c4cometrue/mystorage/dto/FolderContentsRequest.java
> +	public static FolderContentsRequest of(Long folderId, long userId) {
이 DTO를 생성하는 곳에서 `new FolderRequest()` 를 하지 않으려고 `of`로 만드신걸까요? 만약 그렇다면 더 좋은 점이 뭐죠?

2023-11-09 14:13 UTC, pear96 commented on src/main/java/com/c4cometrue/mystorage/dto/FolderNameChangeRequest.java
> +	Long folderId,
폴더의 이름을 바꾸는 경우에도 Null일 수 있나요?

2023-11-09 14:13 UTC, pear96 commented on src/main/java/com/c4cometrue/mystorage/folder/FolderDataAccessService.java
> +public class FolderDataAccessService implements FolderReader, FolderWriter {
Repository를 FolderService가 아닌 DataAccessService에서 의존하며 분리하신 이유가 있을까요?

2023-11-09 14:13 UTC, pear96 commented on src/main/java/com/c4cometrue/mystorage/file/FileController.java
> -	@PostMapping
Metadata 컨트롤러로 인해 파일 업로드를 이동하셨군요..
그리고 메타데이터 서비스가 파일과 폴더 서비스를 다시 의존하고 있군요..

2023-11-09 14:13 UTC, pear96 commented on src/main/java/com/c4cometrue/mystorage/folder/FolderController.java
> +public class FolderController {
생각해보니 유효성 검사 어노테이션이 없군요.. 유효성 검사에 문제가 없었나요?

2023-11-09 14:13 UTC, pear96 commented on src/main/java/com/c4cometrue/mystorage/file/FileService.java
> +		Path path = Paths.get(basePath, storedFileName);
헐 저도 `get`으로 바꿔야겠다.... 계속 `resolve()` 해주고 있었는데...

2023-11-09 14:13 UTC, pear96 commented on src/main/java/com/c4cometrue/mystorage/folder/FolderController.java
> +		folderService.createBy(req.userId(), req.userFolderName(), req.parentId());
(정답은 모름 그냥 같이 고민하자는 뜻)
Service에 DTO를 바로 넘기는 것과 parsing해서 넘기는 것 중 어느게 더 좋은거란게 있을까요?

2023-11-09 14:13 UTC, pear96 commented on src/test/java/com/c4cometrue/mystorage/file/FileDataAccessServiceTest.java
> +		assertThrows(ServiceException.class, () -> fileDataAccessService.deleteBy(FILE_ID));
원하는 exception의 이름이 맞는지 확인하는 검증 단계가 있으면 좋을 것 같아요

2023-11-09 14:13 UTC, pear96 commented on src/test/java/com/c4cometrue/mystorage/folder/FolderDataAccessServiceTest.java
> +		then(folderRepository).should(times(1)).findByParentIdAndUploaderId(null, USER_ID);
`verify` 대신 `then`을 쓰신 이유가 궁금합니다

2023-11-09 17:39 UTC, kochungcheon commented on gradlew.bat
> +@rem you may not use this fileMetadata except in compliance with the License.
아 기존 metadata를 전체 바꿈 단축기로 fileMetadata 로 바꿨었는 데 그것때문에 발생만 문제 같습니다
다시 push 하겠습니다

2023-11-09 17:39 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/file/FileDataAccessService.java
> +	public FileMetadata findBy(Long fileId, Long userId) {
악성 유저가 다른 사람의 파일에 접근하는 것을 막고자 의도 했습니다!

2023-11-09 17:39 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/file/FileDataAccessService.java
> +	public FileMetadata findBy(Long fileId, Long userId) {
delete의 경우 FileService 에서 유저가 해당 파일 소유주인지 확인을 한 다음 오기 때문에 별도로 userId 는 추가 하지 않았습니다!

2023-11-09 17:39 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/folder/FolderMetadata.java
> +	private MetadataType metadataType;
앗..!! 그렇습니다! 수정하겠습니다

2023-11-09 17:39 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/meta/MetadataService.java
> +		return Stream.concat(
아아..!!! 다 보여 줄 필요가 없군요 고민해보겠습니다!

2023-11-09 17:39 UTC, kochungcheon commented on src/main/resources/application.yml
넵 알겠습니다!

2023-11-09 17:39 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/folder/FolderDataAccessService.java
> +		folderMetadata.changeFolderName(folderName);
아 UUID 로 생성 해도 충돌 될 경우가 존재하군요 ..! 수정하겠습니다!

2023-11-09 17:39 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/folder/FolderController.java
> +		folderService.createBy(req.userId(), req.userFolderName(), req.parentId());
뒤의 인자들로 만들어진다 라는 의미였는 데 
이곳에서는 createFolder 라고 표현하는 게 더 좋을 거 같습니다

2023-11-09 17:39 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/meta/MetadataService.java
> +public class MetadataService {
폴더 서비스와 파일 서비스에서 발생한 의존성을 별도로 관리하고 싶어 만들었습니다!

2023-11-09 17:39 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/meta/MetadataController.java
> +	public ResponseEntity<List<MetaResponse>> getFolderContents(FolderContentsRequest req) {
이 부분에서 고민을 좀 많이 해봤는 데 
파일과 폴더는 의존성이 생길 수 밖에 없는 관계네요 의존성 형성하는 방향으로 가고 
컨트롤러 위치도 그에 맞게 수정하겠습니다

2023-11-09 17:39 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/file/FileRepository.java
>  	@Query("SELECT CASE WHEN COUNT(m) > 0 "
오 감사합니다

2023-11-09 17:39 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/util/FolderUtil.java
> +			Files.createDirectories(path);
아아 폴더 경로가 중복될 수 있군요 UUID 로 대비된다 생각했는 데 
UUID 로 생성된 폴더 경로가 중복일 경우 다시 생성 하는 로직이 필요하겠네요

2023-11-09 17:39 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/meta/MetadataController.java
> +	@ResponseStatus(HttpStatus.CREATED)
위의 코멘트 처럼 수정하겠습니다!

2023-11-09 17:39 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/file/FileDataAccessService.java
> +	public List<FileMetadata> findChildBy(Long parentId, Long userId) {
좀더 설명 부탁드려도 되나요!? 
fileId는 Unique 라는 부분을 이해못했습니다..

2023-11-09 17:39 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/folder/FolderRepository.java
> +	List<FolderMetadata> findByParentIdAndUploaderId(Long parentId, Long userId);
오 복합키.! 도입하겠습니다 그리고 이걸로 바꾸었을때 어떤 장점있을 지도 한번 파악해보겠습니다

2023-11-09 17:39 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/file/FileRepository.java
> +		+ "(m.parentId = :parentId OR (m.parentId IS NULL AND :parentId IS NULL)) "
넵 추가하겠습니다!

2023-11-09 17:39 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/folder/FolderWriter.java
> +public interface FolderWriter {
이 부분은 많이 고민 됩니다 
결합도를 낮출수있어 가져오는 장점과 Reader, Writer 를 통해 해당 메서드가 어떤 역할을 하는지  알려줄수있다는 장점에서요 
흡 좀 더 고민 해보겠습니다!

2023-11-09 17:39 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/dto/FolderContentsRequest.java
> +	@NotNull(message = "사용자 id는 널이 될 수 없습니다") long userId
폴더 id 가 null 일 시 최상단 부모를 의미하게 했습니다! 그리고 userId 가 null 이 될 수 없게 했기 때문에 @NotNull 과 long 을 썼습니다

2023-11-09 17:39 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/dto/FolderNameChangeRequest.java
> +	Long folderId,
오 아닙니다! 수정하겠습니다!

2023-11-09 17:39 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/file/FileController.java
> -	@PostMapping
파일과 폴더 서비스에 의존성이 생기는 게 자연스러운가 생각해서 
Metadata 서비스를 만들어서 의존을 관리하고자 했습니다
지금 생각해보니 
네이밍이 MetadataFasade 쪽으로 됐어야 하고 
파일과 폴더 사이 의존에 대해 좀 더 생각해봐야겠네요

2023-11-09 17:39 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/folder/FolderDataAccessService.java
> +public class FolderDataAccessService implements FolderReader, FolderWriter {
비지니스로직과 데이터를 처리하는 로직을 분리하고 싶었습니다!

2023-11-09 17:39 UTC, kochungcheon commented on src/test/java/com/c4cometrue/mystorage/folder/FolderDataAccessServiceTest.java
> +		then(folderRepository).should(times(1)).findByParentIdAndUploaderId(null, USER_ID);
https://brunch.co.kr/@springboot/292 부분 때문에요 사실 어떤 게 좋은 지 모르겠습니다

2023-11-09 17:39 UTC, kochungcheon commented on src/test/java/com/c4cometrue/mystorage/file/FileDataAccessServiceTest.java
> +		assertThrows(ServiceException.class, () -> fileDataAccessService.deleteBy(FILE_ID));
오 그러면 확실히 의도한 에러가 나온 지 알 수 있는 장점이 있네요

2023-11-09 17:39 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/folder/FolderController.java
> +		folderService.createBy(req.userId(), req.userFolderName(), req.parentId());
> (정답은 모름 그냥 같이 고민하자는 뜻) Service에 DTO를 바로 넘기는 것과 parsing해서 넘기는 것 중 어느게 더 좋은거란게 있을까요?

그 부분에 대해 많은 의견이 갈리는 거 같더라고요
현재는 컨트롤러 까지 받아오는 걸 DTO 로 하고 있습니다. parsing 했을 때 장점은 명확하게 인자가 보이니 (ex. add(int a, int b) )Service 레이어에서 인자들을 보면서 작업하기 용이 하다는 것을 들 수 있을 거 같아요 DTO 를 통째로 넘기면 어떤 장점이 있을 까요

2023-11-09 17:39 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/dto/FileUploadRequest.java
> +public record FileUploadRequest(@NotNull(message = "파일을 전달해주세요") MultipartFile multipartFile,
> `@NotNull`로 바꾸셨군요! 그런데 저는 테스트해보면 다른 입력값은 `MethodArgumentNotValidException`가 발생하는데 Multipartfile은 파일을 담지 않고 보내면 `ConstraintViolationException`가 발생하더라구요. 예외 핸들러에서 한번에 처리해줄 수 없는데 청천님은 어떻게 하려고 하셨나요..



> `@NotNull`로 바꾸셨군요! 그런데 저는 테스트해보면 다른 입력값은 `MethodArgumentNotValidException`가 발생하는데 Multipartfile은 파일을 담지 않고 보내면 `ConstraintViolationException`가 발생하더라구요. 예외 핸들러에서 한번에 처리해줄 수 없는데 청천님은 어떻게 하려고 하셨나요..

예외에 많이 미진해서 하은님 코드 보며 많이 배우고 있습니다!

2023-11-09 17:39 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/folder/FolderController.java
> +public class FolderController {
> 생각해보니 유효성 검사 어노테이션이 없군요.. 유효성 검사에 문제가 없었나요?

이 부분도 위에서 언급했 듯 많이 배우고 있습니다 감사합니다!

2023-11-09 17:39 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/dto/FolderContentsRequest.java
> +	public static FolderContentsRequest of(Long folderId, long userId) {
https://tecoble.techcourse.co.kr/post/2020-05-26-static-factory-method/
메서드 명 가지는 장점이 있습니다. 메서드 내에서 제가 자유롭게 에러 코드를 던진다던가 다양하게 생성을 할 수 있다는 행위가 가능해서 new 보다는 of를 선호합니다

2023-11-09 17:39 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/folder/FolderController.java
> +public class FolderController {
> 생각해보니 유효성 검사 어노테이션이 없군요.. 유효성 검사에 문제가 없었나요?

@Vaild 생각보다 재밌는 내용이 많군요 감사합니다!

2023-12-23 06:57 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/folder/FolderWriter.java
> +public interface FolderWriter {
> 2개 이상의 구현체가 있지 않은 상황에서, 굳이 Interface를 만들어야 할지에 대한 의문이 들어요. 특히나 Reader, Writer 모두 하나의 Service로 때려박은 상황에선 더더욱요.

인터페이스 제거하였습니다!

2023-12-23 07:06 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/folder/FolderDataAccessService.java
> +		folderMetadata.changeFolderName(folderName);
> 변경한 이름이 충돌되지 않는지는 확인하지 않네요.

현재 폴더는 사용자가 저장한 이름과 서버에 저장용 이름 이렇게 두개로 저장됩니다 
 changeFolderNameBy 라는 메소드는 사용자가 저장한 이름을 바꾸는 메소드 입니다
이 경우에도 변경 이름이 충돌되는 지 검사 하는 게 좋을 까요!?

2023-12-28 07:17 UTC, merged