Feature/haeun step2
C4-ComeTrue/my-storage pull request #7
Opened 2023-11-07 18:46 UTC by pear96

[FolderMetaData] - 폴더 메타 데이터
- 폴더 pk
- 폴더 이름 / 사용자 이름
- 폴더 경로 (폴더 이름을 포함한 절대 경로)
- 부모 폴더 pk (findAllByParentFolderId를 위해 인덱스 설정)
- 폴더 이름 변경을 위해 폴더 이름과 경로를 바꿔주는 메서드 구현

[FolderRepository]
- 폴더 아이디를 기반으로 폴더의 경로만 찾아오는 메서드는 파일의 경로를 찾을 때 필요합니다. 파일에는 더 이상 절대 경로가 아닌 서버 파일명만 저장하고, 해당 파일을 실제로 읽을 때에는 `해당 파일이 존재하는 폴더의 경로 + 파일명`으로 읽습니다. 폴더 경로 외의 다른 정보는 불필요하므로 쿼리를 작성했습니다.
- (사용자 이름 + 폴더 이름 + 부모 폴더 pk) 로 폴더 데이터를 조회하는 이유는, 폴더 중복 생성을 막기 위함입니다.

[FolderService]
- 조회, 생성, 수정 모두 **부모 폴더를 확인한** 뒤 로직을 수행합니다.
- 부모 폴더 확인을 위해 모든 폴더 응답에는 폴더의 기본키를 포함했습니다. (다른 정보로 바꿔야할까요..)
- 폴더 데이터 조회
  폴더의 이름, 사용자 이름, 하위 폴더 목록(폴더 이름, 사용자 이름), 하위 파일 목록을 반환합니다.
- 폴더 생성
  1. 부모 확인, 중복 확인
  2. 부모 경로 + 폴더 이름 = 폴더 경로
  3. 폴더 생성
  4. 폴더 데이터 저장
- 폴더 이름 수정
  - 가장 고민이 많았던 부분입니다. 결과적으로는 하위 폴더의 경로 변경을 위해 **BFS**를 선택했습니다. 그러나 하위 폴더의 기본키를 부모 폴더 키로 가진 폴더들을 계속 확인한다는 점에서 DB에 매우 많은 요청이 갈 수 있기 때문에 불안합니다...
  - 만약 폴더에 절대 경로를 저장하지 않는다면 폴더 이름만 바꾸면 되겠지만, 그럼 폴더 경로를 조회하기 위해 매번 루트 폴더를 DFS로 탐색해야 한다고 생각했습니다. 조회가 무거운 것 보다는 수정이 무거운게 나을 것 같아서 폴더 명을 수정하면 하위 폴더들의 경로를 수정하도록 구현했습니다.
  - BFS 탐색에 사용하려고 FolderInfo라는 내부 클래스를 만들었습니다.

[ExceptionHandlingController]
@Valid 어노테이션으로 인해 발생하는 MethodArgumentNotValidException 처리를 추가했습니다.
사실은 ServiceException과 그 외는 전부 500으로만 처리하고 싶어서 AOP를 적용해 MethodArgumentNotValidException와 ValidationException가 발생하면 ServiceException을 던지게 하려고 했습니다. 그러나 @AfterThrow에서 어떤 예외인지 판별할 수 없어서 결국 메서드 내에서 분리해야했고 이는 의미가 없다 판단해 ExceptionHandlingController에 분리해서 작성했습니다. UnchekedException이지만 500이 아닌 400 응답코드를 반환해야하는데 고민입니다.

그외 파일 로직에 폴더 아이디를 추가하고, 테스트 코드를 작성했습니다.

2023-11-08 18:15 UTC, kochungcheon reviewed
고생하셨습니다! 특히 개별 유저 마다 폴더 만들어 준다는 전략 인상 깊게 봤습니다 많이 배우고 갑니다!

2023-11-08 18:15 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/dto/request/UploadFileReq.java
> +	@NotNull(message = "folder id is null") Long folderId
long 으로 하는 건 어떤 가요

2023-11-08 18:15 UTC, kochungcheon commented on src/test/java/com/c4cometrue/mystorage/TestParameter.java
>      public static final MultipartFile mockMultipartFile = mock(MultipartFile.class);
상수는 대문자로 표기하는 거 어떤가요

2023-11-08 18:15 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/controller/FolderController.java
> +	@GetMapping()
() 제거 하는 거 어떤 가요

2023-11-08 18:15 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/entity/FileMetaData.java
> +	private long fileId;
id 는 Long 으로 하는 거 어떤가요
https://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#entity-pojo-identifier

2023-11-08 18:15 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/repository/FolderRepository.java
> +@Repository
이 부분은 없어도 될 거 같아요!

2023-11-08 18:15 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/service/FileService.java
> +		String fileStorageName = UUID.randomUUID() + file.getOriginalFilename();
UUID생성은 다른 메서드나 File 엔티티 안에서 처리 하는 거 어떤 가요

2023-11-08 18:15 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/service/FileService.java
> +	@Transactional
트랜잭션이 오래 열릴 수도 있을 거 같아요
예를 들어 대용량 파일을 업로드할 때를 들 수 있을 거 같아요

2023-11-08 18:15 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/service/FileService.java
> +		if (!file.exists()) {
별도로 분리하는 건 어떤 가요

2023-11-08 18:15 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/service/FolderService.java
> +	public void updateFolderName(UpdateFolderNameReq updateFolderNameReq) {
해당 메서드가 담당하는 역할이 많은 거 같아요 분할 하는 건 어떤 가요

2023-11-08 18:15 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/service/FolderService.java
> +	public void updateFolderName(UpdateFolderNameReq updateFolderNameReq) {
루트 폴더나 정말 많은 하위 폴더나 파일을 가진 폴더의 이름을 바꾸게 되면 트랜잭션이 오래 열리게 될 거 같아요 그리고 다 바꾸는 데 발생하는 비용도 상당할 거 같아요

2023-11-09 15:34 UTC, pear96 commented on src/main/java/com/c4cometrue/mystorage/dto/request/UploadFileReq.java
> +	@NotNull(message = "folder id is null") Long folderId
헐 그러게요 계속 pk는 long으로 하고 있었는데 이걸 이렇게.. 잡아주셔서 감사합니다.

2023-11-09 15:37 UTC, pear96 commented on src/test/java/com/c4cometrue/mystorage/TestParameter.java
>      public static final MultipartFile mockMultipartFile = mock(MultipartFile.class);
아 그러게요! 좋은 질문? 지적? 감사합니다.
![수정됨_72934_74447_5624](https://github.com/C4-ComeTrue/my-storage/assets/80267948/92cad910-cf82-4ffe-a589-4e85bb0d1703)

2023-11-09 15:41 UTC, pear96 commented on src/main/java/com/c4cometrue/mystorage/controller/FolderController.java
> +	@GetMapping()
ㅋㅋㅋㅋㅋ 아주 좋습니다! (하 왜 자꾸 이러지..)

2023-11-09 15:59 UTC, pear96 commented on src/main/java/com/c4cometrue/mystorage/entity/FileMetaData.java
> +	private long fileId;
음 이해했습니다.
만약 long으로 하면 기본값이 0으로 초기화 되는데, 여러 엔티티를 동시에 저장하다 문제가 생겨버려서 모두 같은 값을 가지게 되어버리면, 문제 지점을 파악하는게 Null인 것 보다 어렵다는 단점이 있군요. 기본 키를 외부에서 주입 받을 수도 있고...
감사합니다!

2023-11-09 16:01 UTC, pear96 commented on src/main/java/com/c4cometrue/mystorage/repository/FolderRepository.java
> +@Repository
JpaRepository를 상속받기 때문이군요

2023-11-09 16:03 UTC, pear96 commented on src/main/java/com/c4cometrue/mystorage/service/FileService.java
> +		String fileStorageName = UUID.randomUUID() + file.getOriginalFilename();
흠.. 메서드 명으로 무엇을 하는지만 알고 실제 작동 코드는 볼 필요가 없어지기 때문인가요??

2023-11-09 16:26 UTC, pear96 commented on src/main/java/com/c4cometrue/mystorage/service/FileService.java
> +		if (!file.exists()) {
적극 반영하겠습니다.

2023-11-09 16:26 UTC, pear96 commented on src/main/java/com/c4cometrue/mystorage/service/FolderService.java
> +	public void updateFolderName(UpdateFolderNameReq updateFolderNameReq) {
저도 그 부분이 걱정스러운데.. 한 값만 바꾸려면 아예 폴더 경로를 DB에 저장하지 말고 폴더를 조회할 때마다 루트까지 타고가야 할 것 같아서요 =.= 음........

2023-11-09 16:26 UTC, pear96 commented on src/main/java/com/c4cometrue/mystorage/service/FolderService.java
> +	public void updateFolderName(UpdateFolderNameReq updateFolderNameReq) {
적극 반영해보겠습니다.

2023-11-09 16:26 UTC, pear96 commented on src/main/java/com/c4cometrue/mystorage/service/FolderService.java
> +		List<FileMetaDataRes> fileResult = new LinkedList<>();
fileResult 는 쿼리로 받아온 결과를 삽입만 하고 반환하는거라 `LinkedList`를 사용했습니다.. for문 순회도 fileList에서 하는거라.. 혹시 제가 이해가 덜 된걸까요

2023-11-09 16:30 UTC, pear96 commented on src/main/java/com/c4cometrue/mystorage/exception/ExceptionHandlingController.java
> +        String errorMessage = exception.getBindingResult().getFieldErrors().stream()
ㅜㅜ 이거 테스트 코드 어케 짜면 좋을까요...

2023-11-09 17:05 UTC, pear96 commented on src/main/java/com/c4cometrue/mystorage/repository/FolderRepository.java
> +@Repository
from 청천

https://www.inflearn.com/questions/227764/extends-jparepository-lt-gt-vs-repository-%EC%A7%88%EB%AC%B8
https://velog.io/@kshired/Spring-%EC%99%9C-JPARepository%EB%8A%94-Repository%EA%B0%80-%ED%95%84%EC%9A%94-%EC%97%86%EC%9D%84%EA%B9%8C-deep-dive-%ED%95%B4%EB%B3%B4%EA%B8%B0

2023-11-20 00:03 UTC, VSFe requested changes

2023-11-20 00:03 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/dto/request/CreateFolderReq.java
> + * DTO for {@link com.c4cometrue.mystorage.entity.FolderMetaData}
👍
근데 그냥 `@See com.c4cometrue.mystorage.entity.FolderMetaData` 라고 쓰는게 나을수도?

2023-11-20 00:03 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/dto/request/GetFolderReq.java
> +public record GetFolderReq(
이건 진짜 그냥 개인적인 스타일이긴 한데 ㅋㅋㅋ

```java
public record GetFolderReq(
	@NotNull long folderId,
	@NotBlank(message = "folder name is blank") String folderName,
	@NotBlank(message = "user name is blank") String userName,
	@NotNull long parentFolderId
) {
}
```
처럼 쓰는게 좀 더 낫더라고요.

2023-11-20 00:03 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/service/UserService.java
> +		Path userFolderPath = storagePathService.createBasicFolderPath(signUpReq.userName());
👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍

다른 그룹에서도 이거 시켰을때 죄다 rootFolderId = -1로 설정하는데, 이러면 PK 설정 관점에서 정말 답이 없어져서 마음이 아팠었습니다...

2023-11-20 00:03 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/service/UserService.java
> +		UserData user = UserData.builder()
요렇게 짧게 갈거면, 사실 builder는 너무 투머치 하죠?

2023-11-20 00:03 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/util/FileUtil.java
> +	public static void createFolder(Path folderPath) {
기왕 javadoc 다는 겸, 나머지 메서드에도 달아주세요.

2023-11-20 00:03 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/service/FolderService.java
> +	private FolderMetaData checkParentFolder(long parentFolderId) {
`check` 라는 네이밍은 존재 여부를 판단하는 (즉, true, false를 반환하는) 의미가 좀 강한 것 같아요.

2023-11-20 00:03 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/service/FolderService.java
> +	private static class FolderInfo {
record

2023-11-20 00:03 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/service/FolderService.java
> +	public void updateFolderName(UpdateFolderNameReq updateFolderNameReq) {
적절하게 캐싱을 쓰면 되겠죠?

2023-11-20 00:03 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/service/FolderService.java
> +		checkParentFolder(getFolderReq.parentFolderId());
사실 이 논리면 상위 폴더 전부 다 조회해야겠죠?

2023-11-20 00:03 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/service/FolderService.java
> +		FileUtil.createFolder(folderPath);
폴더를 물리적으로 만들 필요가 있을까요?
막말로 모든 파일을 전부 하나의 물리적 폴더에 때려 박아도 상관 없지 않을까요?
(폴더 내에 파일이 엄청나게 많은 상황에서 폴더 이동 과업을 수행하게 되면, Disk I/O가 미친듯이 발생하겠죠.)

2023-11-20 00:03 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/service/FolderService.java
> +		while (!folderIdList.isEmpty()) {
별도의 함수로 분리하고 재귀함수 및 Stream을 사용하면, 훨씬 깔끔한 코드 작성이 가능합니다.
자세한건 나중에...

2023-11-20 00:03 UTC, VSFe commented on src/main/java/com/c4cometrue/mystorage/repository/FileRepository.java
> +	Optional<FileMetaData> findByFileNameAndUserNameAndFolderId(String filename, String username, long folderId);
인덱스가 필요할 것 같은데요.

2023-11-27 12:46 UTC, pear96 commented on src/main/java/com/c4cometrue/mystorage/dto/request/CreateFolderReq.java
> + * DTO for {@link com.c4cometrue.mystorage.entity.FolderMetaData}
사실 intellij에서 DTO로 만들어서 자동 생성된 주석이었는데.. 
`@link`는 인라인으로, `@see` 는 독립적인 블록으로 생성된다는 차이점이 있군요
DTO들은 다 Entity 기반으로 생성한거고 특별한 설명이 필요 없으니 `@see`만 써도 되겠군요.
https://stackoverflow.com/questions/10097199/javadoc-see-or-link

2023-11-27 12:48 UTC, pear96 commented on src/main/java/com/c4cometrue/mystorage/dto/request/GetFolderReq.java
> +public record GetFolderReq(
호오 그렇군요..!

2023-11-27 12:59 UTC, pear96 commented on src/main/java/com/c4cometrue/mystorage/service/UserService.java
> +		Path userFolderPath = storagePathService.createBasicFolderPath(signUpReq.userName());
와우 무한 붐업을 받다니 행복하군요 ^__^

2023-11-27 13:06 UTC, pear96 commented on src/main/java/com/c4cometrue/mystorage/service/UserService.java
> +		UserData user = UserData.builder()
음 맞는 말입니다... 인자가 1개 뿐이니... 생성자로 생성하는게 가독성에도 효율면에서도 좋을 것 같아요

2023-11-27 13:08 UTC, pear96 commented on src/main/java/com/c4cometrue/mystorage/util/FileUtil.java
> +	public static void createFolder(Path folderPath) {
🤓 네 적극 반영하겠습니다

2023-11-27 14:05 UTC, pear96 commented on src/main/java/com/c4cometrue/mystorage/repository/FileRepository.java
> +	Optional<FileMetaData> findByFileNameAndUserNameAndFolderId(String filename, String username, long folderId);
지당하신 말씀입니다..
생각해보니 folderId(중복 안됨, long) -> userName(중복 안됨, String) -> fileName(중복 가능, String) 순으로 index를 생성하면 더 효율적일 것 같더라구요. 그래서 메서드와 파라미터 순서도 바꿨습니다. 💡

2023-11-27 14:06 UTC, pear96 commented on src/main/java/com/c4cometrue/mystorage/service/FolderService.java
> +		FileUtil.createFolder(folderPath);
으아 그러게요 파일 명을 물리적 서버에 저장한 이름과 DB에 원본 이름, 저장소 이름 둘 다 저장하는건 생각했었는데 왜 꼭 파일 트리를 맞춰야한다고 생각했을까요... 좋은 생각이네요

2023-11-27 14:07 UTC, pear96 commented on src/main/java/com/c4cometrue/mystorage/service/FolderService.java
> +		checkParentFolder(getFolderReq.parentFolderId());
하하하하하..... 맞아요... 좀 더 고민해보겠습니다.

2023-11-28 07:40 UTC, pear96 commented on src/main/java/com/c4cometrue/mystorage/service/FolderService.java
> +	public void updateFolderName(UpdateFolderNameReq updateFolderNameReq) {
폴더를 DB에서만 저장하고 물리적 폴더를 생성하지 않는 것으로 바꿨습니다.
그래서 해당 폴더의 이름만 바꾸면 되기 때문에 하위 폴더는 수정할 일이 없습니다.

2023-12-04 11:20 UTC, pear96 commented
### 폴더가 제대로 존재하는지(부모 폴더를 타고 올라가서 root까지 닿는지) 확인해야 할까요?

폴더가 제대로 존재하는지 확인하려면 최상위까지 타고 올라가봐야하는데, 
이걸 한다면 폴더, 파일의 모든 로직마다 수행해야합니다.

[확인한다.]
- 요청이 많으면 병목 생기기 딱 좋음. 시간이 매우 많이 소요될 수 있을 것 같습니다..
- 스스로를 부모 폴더로 보면 안되기 때문에 이제까지 지나온 폴더들이랑 겹치지 않는지도 확인해야합니다. (HashSet..?)
- 아니면 확인된 폴더들은 캐시에 저장해두고 활용할 수도 있으나... 이 또한 수정이 생기면 반영이 되어야하는데 데이터가 캐시도 온전하지 않을 수 있을 것 같아요
- 게다가 폴더 소유주도 확인해야합니다. (권한 문제)

[확인하지 않는다.]
- 속도는 빠르지만, 폴더가 중간에 끊겨있을 수 있습니다.
- 그런데 그게 큰 문제가 되나? 사실 이것도 판단이 잘 안됩니다.
  - 폴더가 끊겨있을 뿐 파일만 제대로 있다면 다운로드에는 문제가 없는데.. (파일도 다운로드 받을 때 실제로 존재하는지 확인해야겠군요..)
  - 연결이 끊겨있다면 조회에서 어차피 막힐텐데, 그럼 더미값이 남아있긴 한다는 문제가 있고...

2023-12-04 11:43 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/entity/UserData.java
> +	@Builder
빌더 패턴과 정적 팩토리 패턴 이 둘을 언제 사용하면 좋을 지 항상 고민이 들던데, 하은님은 어떤 기준으로 이 둘을 사용하시나요

2023-12-04 11:43 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/service/FileService.java
> +		String fileStorageName = UUID.randomUUID() + file.getOriginalFilename();
그렇습니다 !

2023-12-04 11:43 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/controller/FileController.java
> +            .body(file.resource());
오 좋은데요 배워갑니다

2023-12-04 11:43 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/service/UserService.java
> +		checkDuplicate(userName);
만약 동시에 유저가 같은 이름으로 회원 가입하면 어떻게 되나요

2023-12-04 11:43 UTC, kochungcheon commented on src/main/java/com/c4cometrue/mystorage/service/UserService.java
> +		checkDuplicate(userName);
동시성 이슈를 처리 할 로직 혹은 락이 필요해보여요

2023-12-05 02:06 UTC, VSFe commented
> ### 폴더가 제대로 존재하는지(부모 폴더를 타고 올라가서 root까지 닿는지) 확인해야 할까요?
> 폴더가 제대로 존재하는지 확인하려면 최상위까지 타고 올라가봐야하는데, 이걸 한다면 폴더, 파일의 모든 로직마다 수행해야합니다.
> 
> [확인한다.]
> 
> * 요청이 많으면 병목 생기기 딱 좋음. 시간이 매우 많이 소요될 수 있을 것 같습니다..
> * 스스로를 부모 폴더로 보면 안되기 때문에 이제까지 지나온 폴더들이랑 겹치지 않는지도 확인해야합니다. (HashSet..?)
> * 아니면 확인된 폴더들은 캐시에 저장해두고 활용할 수도 있으나... 이 또한 수정이 생기면 반영이 되어야하는데 데이터가 캐시도 온전하지 않을 수 있을 것 같아요
> * 게다가 폴더 소유주도 확인해야합니다. (권한 문제)
> 
> [확인하지 않는다.]
> 
> * 속도는 빠르지만, 폴더가 중간에 끊겨있을 수 있습니다.
> * 그런데 그게 큰 문제가 되나? 사실 이것도 판단이 잘 안됩니다.
>   
>   * 폴더가 끊겨있을 뿐 파일만 제대로 있다면 다운로드에는 문제가 없는데.. (파일도 다운로드 받을 때 실제로 존재하는지 확인해야겠군요..)
>   * 연결이 끊겨있다면 조회에서 어차피 막힐텐데, 그럼 더미값이 남아있긴 한다는 문제가 있고...

여기서는 보정하지 말고 넘어갑시다.

일반적으로는 별도의 정합성 배치를 개발해서 보정하죠?

2023-12-05 06:42 UTC, pear96 commented on src/main/java/com/c4cometrue/mystorage/entity/UserData.java
> +	@Builder
웬만하면 Builder를 우선으로 썼는데, 필드 수가 적어서 별로 헷갈리지 않는다면 정적 패토리 메서드가 가독성이 더 좋은 것 같긴합니다.

2023-12-06 09:53 UTC, pear96 commented on src/main/java/com/c4cometrue/mystorage/service/UserService.java
> +		checkDuplicate(userName);
https://www.inflearn.com/questions/59250/%EC%95%88%EB%85%95%ED%95%98%EC%84%B8%EC%9A%94-unique-index-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%A0%80%EC%9E%A5%EC%97%90-%EB%8C%80%ED%95%B4%EC%84%9C-%EC%A7%88%EB%AC%B8%EB%93%9C%EB%A6%BD%EB%8B%88%EB%8B%A4

이에 따라 unique를 적용하기로 했습니다. (디코 채팅에서 남겨줬었던거 봤어요 땡큐)

2023-12-07 17:01 UTC, VSFe approved these changes
일단 코멘트 더 달고 싶긴 한데... 너무 붙잡아두긴 뭐하니까 스텝 3에서 마저 이야기 합시다.

2023-12-10 13:00 UTC, merged